### ISSUE TITLE
Why the code does not have attention mask?

### ISSUE THREAD

**Issue by hrwise-nlp** [pkchat-focus/FoCus#4]
Hello, very nice work.

I am wondering why there is no attention mask while decoding.

**Comment by pkchat-focus** [comment]
Please see the codes of transformers 4.10.0. [GPT2](https://huggingface.co/transformers/v4.10.1/model_doc/gpt2.html#gpt2model), [BART](https://huggingface.co/transformers/v4.10.1/model_doc/bart.html).

In the examples, attention masks are not specified, because the attention masks are created if they don't exist.

Our codes are based on the Huggingface's model and please refer to their released codes if you want to see the language models.

Thank you!
